from scanner.forms import extract_forms_from_html
from scanner.http_client import HttpClient
from difflib import SequenceMatcher


CSRF_KEYWORDS = ["csrf", "_csrf", "token", "authenticity_token", "__requestverificationtoken"]
HEADER_BASED_CSRF_HINTS = [
    "x-csrf-token",
    "x-xsrf-token",
    "csrf-token",
    "xsrf-token",
]
META_CSRF_NAMES = ["csrf-token", "csrf_token", "xsrf-token", "_csrf"]

# Tokens generated by common frameworks – used to detect if server validates uniqueness
_FORGED_TOKEN = "bh_csrf_forged_00000000"


def build_field_blob(field):
    return " ".join([
        str(field.get("name", "")),
        str(field.get("id", "")),
        str(field.get("placeholder", "")),
        str(field.get("aria_label", "")),
        str(field.get("type", "")),
    ]).lower()


def has_meta_csrf_hint(html):
    lower = (html or "").lower()
    return any(
        f'name="{name}"' in lower or f"name='{name}'" in lower
        for name in META_CSRF_NAMES
    )


def has_header_based_csrf_hint(html):
    lower = (html or "").lower()
    return any(marker in lower for marker in HEADER_BASED_CSRF_HINTS)


def _response_looks_rejected(resp, original_resp) -> bool:
    """True if the server actually rejected the request (token validation working)."""
    if resp is None:
        return False
    # 4xx / 5xx → rejected
    if resp.status_code in (400, 401, 403, 405, 419, 422, 500):
        return True
    # Redirect to the same page or a login/error page → likely rejected
    final_url = str(getattr(resp, "url", "") or "")
    if any(kw in final_url.lower() for kw in ("login", "signin", "error", "forbidden", "csrf")):
        return True
    # Significant content difference → server responded differently (e.g., error message shown)
    orig_len = len(original_resp.text or "") if original_resp else 0
    new_len = len(resp.text or "")
    if orig_len > 0:
        ratio = SequenceMatcher(None, original_resp.text or "", resp.text or "").ratio()
        if ratio < 0.6 and abs(orig_len - new_len) > 100:
            return True
    return False


def _attempt_csrf_bypass(client: HttpClient, form: dict, csrf_field_name: str, page_url: str):
    """
    Attempt to submit a form bypassing CSRF protection in two ways:
    1. Remove the CSRF token field entirely.
    2. Submit with a forged (invalid) token value.

    Returns (bypassed: bool, method: str, evidence: str)
    """
    action = form.get("action") or page_url
    fields = form.get("fields") or []

    # Build baseline data (valid submission – only to compare response shape)
    base_data = {}
    for f in fields:
        name = f.get("name") or ""
        if not name:
            continue
        ftype = (f.get("type") or "").lower()
        if ftype in ("submit", "button", "reset", "file"):
            continue
        base_data[name] = f.get("value") or ("test@example.com" if ftype == "email" else "test_value")

    # Attempt 1: omit the CSRF token entirely
    data_no_token = {k: v for k, v in base_data.items() if k != csrf_field_name}
    try:
        resp_no_token = client.post(action, data=data_no_token)
        # Get a fresh baseline to compare against (new session may have different content)
        try:
            baseline = client.get(page_url)
        except Exception:
            baseline = None
        if not _response_looks_rejected(resp_no_token, baseline):
            return True, "omitido", (
                f"POST a {action} sin campo '{csrf_field_name}' devolvió HTTP "
                f"{resp_no_token.status_code}. El servidor NO rechazó la petición."
            )
    except Exception:
        pass

    # Attempt 2: submit with a forged token
    data_forged = dict(base_data)
    data_forged[csrf_field_name] = _FORGED_TOKEN
    try:
        resp_forged = client.post(action, data=data_forged)
        try:
            baseline = client.get(page_url)
        except Exception:
            baseline = None
        if not _response_looks_rejected(resp_forged, baseline):
            return True, "token_forjado", (
                f"POST a {action} con token forjado '{_FORGED_TOKEN}' devolvió HTTP "
                f"{resp_forged.status_code}. El servidor NO rechazó el token inválido."
            )
    except Exception:
        pass

    return False, "", ""


def scan_csrf_from_pages(pages):
    client = HttpClient()
    results = []
    runtime_auth_like_pages = 0

    for page in pages:
        page_url  = page.get("url") or page.get("final_url") or ""
        page_html = page.get("html") or page.get("rendered_html") or ""
        if not page_url:
            continue
        runtime_inputs = page.get("browser_inputs") or (page.get("browser_runtime") or {}).get("inputs") or []
        if runtime_inputs:
            combined = str(runtime_inputs).lower()
            has_password = "password" in combined or "contraseña" in combined
            has_user = any(token in combined for token in ["email", "correo", "usuario", "user", "login"])
            if has_password and has_user:
                runtime_auth_like_pages += 1

        meta_hint = has_meta_csrf_hint(page_html)
        header_hint = has_header_based_csrf_hint(page_html)
        forms = extract_forms_from_html(page_url, page_html)

        for form in forms:
            if form["method"] != "POST":
                continue

            field_names = [str(f.get("name", "")).lower() for f in form["fields"]]

            csrf_field_name = None
            for f in form["fields"]:
                blob = build_field_blob(f)
                if (f.get("type", "")).lower() == "hidden" and any(kw in blob for kw in CSRF_KEYWORDS):
                    csrf_field_name = f.get("name") or f.get("id") or ""
                    break
            has_hidden_token = csrf_field_name is not None

            has_any_token_like_field = any(
                any(keyword in build_field_blob(f) for keyword in CSRF_KEYWORDS)
                for f in form["fields"]
            )

            if has_hidden_token:
                # CRITICAL: Verify the server ACTUALLY validates the token, not just its presence
                bypassed, bypass_method, bypass_evidence = _attempt_csrf_bypass(
                    client, form, csrf_field_name, page_url
                )
                if bypassed:
                    results.append({
                        "control": f"Protección CSRF - formulario {form['index']}",
                        "status": "Hallazgo",
                        "severity": "Alta",
                        "description": (
                            f"Token anti-CSRF presente en el formulario HTML, pero el servidor "
                            f"NO lo valida server-side (bypass por {bypass_method})."
                        ),
                        "evidence": bypass_evidence,
                        "recommendation": (
                            "El token debe generarse por sesión, transmitirse en cada petición y "
                            "verificarse server-side comparando con el valor almacenado en sesión. "
                            "Verificar que el middleware CSRF está activo en todos los endpoints."
                        ),
                    })
                else:
                    results.append({
                        "control": f"Protección CSRF - formulario {form['index']}",
                        "status": "Correcto",
                        "severity": "Informativa",
                        "description": (
                            "Token anti-CSRF presente Y validado server-side: "
                            "el servidor rechazó tanto la petición sin token como la de token forjado."
                        ),
                        "evidence": (
                            f"Página: {page_url} | Action: {form['action']} | "
                            f"Campo CSRF: {csrf_field_name}"
                        ),
                        "recommendation": "Mantener rotación de tokens por petición (double-submit o synchronizer token).",
                    })
            elif has_any_token_like_field or meta_hint:
                results.append({
                    "control": f"Protección CSRF - formulario {form['index']}",
                    "status": "Comprobado",
                    "severity": "Baja",
                    "description": (
                        "Se detectaron indicios de protección CSRF (campo o meta), "
                        "pero el campo no es de tipo hidden o no se pudo verificar server-side."
                    ),
                    "evidence": (
                        f"Página: {page_url} | Action: {form['action']} | "
                        f"Campos: {', '.join(field_names)} | Meta CSRF: {meta_hint}"
                    ),
                    "recommendation": "Confirmar validación server-side del token y revisar SameSite/Origin/Referer.",
                })
            elif header_hint:
                results.append({
                    "control": f"Protección CSRF - formulario {form['index']}",
                    "status": "Posible hallazgo",
                    "severity": "Media",
                    "description": (
                        "No se observó token CSRF en el formulario POST. "
                        "La página sugiere protección basada en cabeceras, no verificada."
                    ),
                    "evidence": (
                        f"Página: {page_url} | Action: {form['action']} | "
                        f"Campos: {', '.join(field_names)}"
                    ),
                    "recommendation": (
                        "Verificar que el backend exija cabecera anti-CSRF y bloquee "
                        "envíos sin cabecera válida."
                    ),
                })
            else:
                results.append({
                    "control": f"Protección CSRF - formulario {form['index']}",
                    "status": "Hallazgo",
                    "severity": "Alta",
                    "description": "Formulario POST sin token anti-CSRF evidente ni protección por cabeceras.",
                    "evidence": (
                        f"Página: {page_url} | Action: {form['action']} | "
                        f"Campos: {', '.join(field_names)}"
                    ),
                    "recommendation": (
                        "Implementar tokens anti-CSRF únicos por sesión y validarlos server-side. "
                        "Usar SameSite=Strict/Lax en cookies de sesión como defensa adicional."
                    ),
                })

    if not results:
        if runtime_auth_like_pages:
            results.append({
                "control": "Protección CSRF",
                "status": "No evidenciado",
                "severity": "Informativa",
                "description": "No se evidenció falta de protección CSRF en formularios HTML POST; se detectaron flujos auth client-side.",
                "evidence": f"Flujos dinámicos detectados: {runtime_auth_like_pages} | Formularios HTML POST: 0",
                "recommendation": "Validar en pruebas activas que el backend exija token/cabecera anti-CSRF en endpoints API de autenticación.",
            })
            return results

        results.append({
            "control": "Protección CSRF",
            "status": "No evidenciado",
            "severity": "Informativa",
            "description": "No se detectaron formularios HTML POST en el alcance analizado.",
            "evidence": "Sin formularios POST.",
            "recommendation": "Ampliar el análisis a rutas autenticadas."
        })

    return results